name: Daily Scrape and Deploy

on:
  schedule:
    # 每天北京时间早上6点（UTC 22:00）
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f scraper/requirements.txt ]; then pip install -r scraper/requirements.txt; fi

      - name: 运行爬虫脚本
        run: python scraper/crawler.py

      - name: 配置 Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 提交并推送更新
        run: |
          git add app/data/programs.json
          git commit -m "chore: 自动更新 programs.json" || echo "No changes to commit"
          git push 